# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'

  # Note that the session will be started ONLY if you read or write from it.
  session: true

  http_client:
    scoped_clients:
      onboarding_user_http_client:
        base_uri: '%onboarding.user_service.base_url%'
        verify_peer: false
        verify_host: false
        headers:
          X-API-TOKEN: '%onboarding.user_service.token%'

      onboarding_organization_http_client:
        base_uri: '%onboarding.organization_service.base_url%'
        verify_peer: false
        verify_host: false
        headers:
          X-API-TOKEN: '%onboarding.organization_service.token%'

  #esi: true
  #fragments: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
