services:
  console:
    build:
      context: .
      dockerfile: docker/tools/Dockerfile
      target: console
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools

  phpcs:
    build:
      context: .
      dockerfile: docker/tools/Dockerfile
      target: phpcs
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools
