services:
  shell:
    image: ${IMAGES_PREFIX:-}shell
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: shell
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools

  phpunit:
    image: ${IMAGES_PREFIX:-}phpunit
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: phpunit
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools

  phpunit-coverage:
    image: ${IMAGES_PREFIX:-}phpunit-coverage
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: phpunit-coverage
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools

  phpcs:
    image: ${IMAGES_PREFIX:-}phpcs
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: phpcs
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools

  phpcbf:
    image: ${IMAGES_PREFIX:-}phpcbf
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: phpcbf
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools

  phpmd:
    image: ${IMAGES_PREFIX:-}phpmd
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: phpmd
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools

  phpstan:
    image: ${IMAGES_PREFIX:-}phpstan
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: phpstan
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools

  psalm:
    image: ${IMAGES_PREFIX:-}psalm
    build:
      context: .
      dockerfile: ./docker/tools/Dockerfile
      target: psalm
      args:
        - PHP_VERSION=${PHP_VERSION:-8.4}
    volumes:
      - .:/var/www/html
    profiles:
      - dev
      - tools
