organization_organizations_registration_number_validation:
  path: /api/organization/organizations/{registrationNumber}/validate
  methods: [ 'GET' ]
  controller: Candice\Organization\Infrastructure\Symfony\Controller\OrganizationController::registrationNumberValidation

organization_organizations_get_organization:
  path: /api/organization/organizations/{registrationNumber}
  methods: [ 'GET' ]
  controller: Candice\Organization\Infrastructure\Symfony\Controller\OrganizationController::get

organization_organizations_register_organization:
  path: /api/organization/organizations
  methods: [ 'POST' ]
  controller: Candice\Organization\Infrastructure\Symfony\Controller\OrganizationController::register
