# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  private_api_token: '%env(string:PRIVATE_API_TOKEN)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  # Shared
  Candice\Shared\:
    resource: '../src/Shared/'
    exclude:
      - '../src/Shared/Infrastructure/Symfony/Kernel.php'

  # Organization
  Candice\Organization\:
    resource: '../src/Organization/'

  Candice\Organization\Domain\Repository\OrganizationRepositoryInterface:
    class: Candice\Organization\Infrastructure\Repository\DoctrineOrganizationRepository

  # Identity and Access
  Candice\IdentityAndAccess\:
    resource: '../src/IdentityAndAccess/'

  Candice\IdentityAndAccess\Infrastructure\Symfony\Security\PrivateApiUserProvider:
    arguments:
      $token: '%private_api_token%'

  Candice\IdentityAndAccess\Domain\Repository\UserRepositoryInterface:
    class: Candice\IdentityAndAccess\Infrastructure\Repository\DoctrineUserRepository

  # Onboarding
  Candice\Onboarding\:
    resource: '../src/Onboarding/'
