# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  # Identity And Access
  iam.private_api_token: '%env(string:IAM_PRIVATE_API_TOKEN)%'

  # Onboarding
  onboarding.organization_service.base_url: '%env(string:ONBOARDING_ORGANIZATION_SERVICE_BASE_URL)%'
  onboarding.organization_service.token: '%env(string:ONBOARDING_ORGANIZATION_SERVICE_API_TOKEN)%'

  onboarding.user_service.base_url: '%env(string:ONBOARDING_USER_SERVICE_BASE_URL)%'
  onboarding.user_service.token: '%env(string:ONBOARDING_USER_SERVICE_API_TOKEN)%'

  # Customer Relationship
  crm.organization_service.base_url: '%env(string:CRM_ORGANIZATION_SERVICE_BASE_URL)%'
  crm.organization_service.token: '%env(string:CRM_ORGANIZATION_SERVICE_API_TOKEN)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  # Shared
  Candice\Shared\:
    resource: '../src/Shared/'
    exclude:
      - '../src/Shared/Infrastructure/Symfony/Kernel.php'

  Candice\Shared\Domain\Event\EventDispatcherInterface:
    class: Candice\Shared\Infrastructure\Symfony\Event\EventDispatcher

  # Organization
  Candice\Organization\:
    resource: '../src/Organization/'

  Candice\Organization\Domain\Repository\OrganizationRepositoryInterface:
    class: Candice\Organization\Infrastructure\Repository\DoctrineOrganizationRepository

  # Identity and Access
  Candice\IdentityAndAccess\:
    resource: '../src/IdentityAndAccess/'

  Candice\IdentityAndAccess\Domain\Repository\UserRepositoryInterface:
    class: Candice\IdentityAndAccess\Infrastructure\Repository\DoctrineUserRepository

  Candice\IdentityAndAccess\Infrastructure\Symfony\Security\PrivateApiUserProvider:
    arguments:
      $token: '%iam.private_api_token%'

  # Onboarding
  Candice\Onboarding\:
    resource: '../src/Onboarding/'

  Candice\Onboarding\Domain\Repository\ApplicationRepositoryInterface:
    class: Candice\Onboarding\Infrastructure\Repository\DoctrineApplicationRepository

  Candice\Onboarding\Domain\Service\OrganizationServiceInterface:
    class: Candice\Onboarding\Infrastructure\Symfony\Service\HttpOrganizationService

  Candice\Onboarding\Domain\Service\UserServiceInterface:
    class: Candice\Onboarding\Infrastructure\Symfony\Service\HttpUserService

  # Customer Relationship
  Candice\CustomerRelationship\:
    resource: '../src/CustomerRelationship/'

  Candice\CustomerRelationship\Domain\Service\OrganizationCheckerInterface:
    class: Candice\CustomerRelationship\Infrastructure\Service\HttpOrganizationChecker
