name: Conformity

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~
  merge_group: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PHP-CS
        run: make phpcs

      - name: Run PHPMD
        run: make phpmd

      - name: Run PHPStan
        run: make phpstan

      - name: Run Psalm
        run: make psalm-check

      - name: Run Deptrac coverage
        run: make deptrac-coverage

      - name: Run Deptrac
        run: make deptrac
